### ISSUE TITLE
General problems with macOS 12 (Monterey)

### ISSUE THREAD

**Issue by exkc** [notAperson535/OneClick-macOS-Simple-KVM#31]
**Describe the bug**
It restart when i try to  boot the installer

**To Reproduce**
Boot the installer image

**Expected behavior**
Boot

**Screenshots**
![Screenshot_20220917-005151_bVNC_Pro](https://user-images.githubusercontent.com/70055899/190691406-8c5035aa-f69b-41a8-b914-14fdfdaad71c.png)

**Desktop (please complete the following information):**
 - OS: Artix + Black Arch Repo + Cachy OS Repo and it is booting off linux-cachyos
 - Version : rolling

**Additional context**
 I added ` -vnc` :0 to the command that used for boot the vm.

**Comment by notAperson535** [comment]
@exkc try doing a `git pull --rebase` as I have recently fixed monterey.

**Comment by exkc** [comment]
I have already cloned the lastest commit.

**Comment by GarciaLnk** [comment]
I can't get the installer of Monterey to boot either, I'm on Fedora 36, I used the one-click setup, here's a screenshot:

![image](https://user-images.githubusercontent.com/4411661/191095666-cc24f9c7-0b04-4127-a9f8-db1ad7026991.png)

**Comment by altagir** [comment]
Same on kubuntu 22.04

**Comment by notAperson535** [comment]
@altagir @GarciaLnk @exkc Try doing a `git pull --rebase` i just pushed a commit to fix Monterey 12.6

**Comment by GarciaLnk** [comment]
> @altagir @GarciaLnk @exkc Try doing a `git pull --rebase` i just pushed a commit to fix Monterey 12.6

for me it didn't fix the issue, the only thing that has changed is that it now bootloops after showing the error

**Comment by altagir** [comment]
I test also and there was no change.
I am able to get BigSur and get booted, but not catalina : 

![191095666-cc24f9c7-0b04-4127-a9f8-db1ad7026991](https://user-images.githubusercontent.com/1028010/192661892-be04f2d2-1149-46e8-91be-89f3f4de2255.png)

**Comment by mibzman** [comment]
I'm seeing the same thing, but on ventura.  Every other version works but ventura does this bootloop.

**Comment by notAperson535** [comment]
@mibzman do a `git pull --rebase` and try again. I fixed Ventura a couple of weeks ago.

**Comment by mibzman** [comment]
@notAperson535 I cloned this repo for the first time yesterday.  I encountered the Ventura bootloop running `62e4369`
